services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped

    ports:
      - "11434:11434"

    volumes:
      - ollama_data:/root/.ollama

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0:11434

    networks:
      - ai-network

  open-webui:
    image: openwebui/open-webui:0.9-cuda
    container_name: open-webui
    restart: unless-stopped

    depends_on:
      - ollama

    ports:
      - "3000:8080"

    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - HF_TOKEN=${HF_TOKEN}

    volumes:
      - open_webui_data:/app/backend/data

    networks:
      - ai-network

networks:
  ai-network:

volumes:
  ollama_data:
  open_webui_data:
